import { v4 as uuid4 } from "uuid"
import { IProduct } from "./types"

export const products: IProduct[] = [
  {
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F1%2FApples.jpg&w=3840&q=75',
    name: 'Apples',
    discountPrice: '$1.60',
    regularPrice: '$2.00',
    offerPercent: '20%',
    amount: 0,
  },
  {
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F8%2FCucumber.jpg&w=3840&q=75',
    name: 'Cucumber',
    discountPrice: '$2.50',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },
  {
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F10%2FDates.jpg&w=3840&q=75',
    name: 'Dates',
    discountPrice: '$8.00',
    regularPrice: '$10.00',
    offerPercent: '20%',
    amount: 0,
  },
  {
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F11%2FFrenchGreenBeans.jpg&w=3840&q=75',
    name: 'French Green Beans',
    discountPrice: '$1.20',
    regularPrice: '$1.50',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F12%2FGreenBeans.jpg&w=3840&q=75',
    name: 'Green Beans',
    discountPrice: '$4.00',
    regularPrice: '$5.00',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F13%2FGreenLimes.jpg&w=3840&q=75',
    name: 'Lime',
    discountPrice: '$1.50',
    regularPrice: '$2.00',
    offerPercent: '25%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F14%2FMangoes.jpg&w=3840&q=75',
    name: 'Mango',
    discountPrice: '$2.50',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F15%2FMiniPeppers.jpg&w=3840&q=75',
    name: 'Pepper',
    discountPrice: '$5.00',
    regularPrice: '$6.00',
    offerPercent: '17%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F16%2Fpears.jpg&w=3840&q=75',
    name: 'Pears',
    discountPrice: '$3.50',
    regularPrice: '$4.00',
    offerPercent: '13%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F17%2FPeeled-Carrots.jpg&w=3840&q=75',
    name: 'Peeled Baby Carrot',
    discountPrice: '$2.20',
    regularPrice: '$2.50',
    offerPercent: '12%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F18%2FRedCherries.jpg&w=3840&q=75',
    name: 'Cherry',
    discountPrice: '$1.80',
    regularPrice: '$2.00',
    offerPercent: '10%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F19%2Fstrawberry.jpg&w=3840&q=75',
    name: 'Strawberry',
    discountPrice: '$8.00',
    regularPrice: '$10.00',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F20%2FVeggiePlatter.jpg&w=3840&q=75',
    name: 'Mix Vegetable Platter',
    discountPrice: '$3.20',
    regularPrice: '$4.00',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F21%2FYellow-Limes.jpg&w=3840&q=75',
    name: 'Lemon',
    discountPrice: '$1.20',
    regularPrice: '$1.50',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F183%2FSignatureSalmon_fstp4m.jpg&w=3840&q=75',
    name: 'Signature Salmon',
    discountPrice: '$4.95',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F185%2Fswordfish_smniuv.jpg&w=3840&q=75',
    name: 'Swordfish Fillet',
    discountPrice: '$7.50',
    regularPrice: '$10.00',
    offerPercent: '25%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F186%2Fhalibut_jaz7ju.jpg&w=3840&q=75',
    name: 'Halibut Fillet',
    discountPrice: '$12.00',
    regularPrice: '$15.00',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F187%2FTilapiaFillet_a2urhk.jpg&w=3840&q=75',
    name: 'Tilapia Fillet',
    discountPrice: '$7.89',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F188%2Fbeef_xkxhnb.jpg&w=3840&q=75',
    name: 'Fresh Beef',
    discountPrice: '$6.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F190%2Fchicken_thigh_yrdfwh.jpg&w=3840&q=75',
    name: 'Chicken Thighs',
    discountPrice: '$7.89',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F191%2Fchicken_brest_ribcxo.jpg&w=3840&q=75',
    name: 'Chicken Breast',
    discountPrice: '$9.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F192%2Fsteak_okxpjo.jpg&w=3840&q=75',
    name: 'Beef Steak',
    discountPrice: '$12.00',
    regularPrice: '$15.00',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F193%2Fbelmont_custard_cream.jpg&w=3840&q=75',
    name: 'Belmont Custard Cream',
    discountPrice: '$5.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F194%2Fcrawford_digestives.jpg&w=3840&q=75',
    name: 'Crawford Digestives',
    discountPrice: '$6.50',
    regularPrice: '$8.00',
    offerPercent: '19%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F195%2Fcrawford_shortie.jpg&w=3840&q=75',
    name: 'Crawford Shortie',
    discountPrice: '$5.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F198%2Fjulis_cheese_crackers.jpg&w=3840&q=75',
    name: 'Juli S Cheese Crackers',
    discountPrice: '$5.00',
    regularPrice: '$8.00',
    offerPercent: '38%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F199%2Fkhong_guan_orange_cream.jpg&w=3840&q=75',
    name: 'Khong Guan Orange Cream',
    discountPrice: '$5.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F200%2Fkhong_guan_premium_marie.jpg&w=3840&q=75',
    name: 'Khong Guan Premium Marie',
    discountPrice: '$6.00',
    regularPrice: '$8.00',
    offerPercent: '25%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F201%2Flotus_biscoff.jpg&w=3840&q=75',
    name: 'Lotus Biscoff',
    discountPrice: '$7.50',
    regularPrice: '$10.00',
    offerPercent: '25%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F202%2Fartiach_filipino.jpg&w=3840&q=75',
    name: 'Filipinos',
    discountPrice: '$4.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F204%2Fcadbury_zip.jpg&w=3840&q=75',
    name: 'Cadbury Zip',
    discountPrice: '$2.90',
    regularPrice: '$4.00',
    offerPercent: '28%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F206%2Fcloetta.jpg&w=3840&q=75',
    name: 'Cloetta Chocowoffle Crispy',
    discountPrice: '$2.50',
    regularPrice: '$3.00',
    offerPercent: '17%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F207%2Fcloetta_sprinkle.jpg&w=3840&q=75',
    name: 'Cloetta Sprinkle',
    discountPrice: '$3.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F208%2Fhersheys_kisses.jpg&w=3840&q=75',
    name: 'Hersheys Kisses',
    discountPrice: '$3.50',
    regularPrice: '$5.00',
    offerPercent: '30%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F209%2Fm%2526m_funsize.jpg&w=3840&q=75',
    name: 'M &amp; M Funsize',
    discountPrice: '$1.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F210%2Fnestle_butterfinger.jpg&w=3840&q=75',
    name: 'Nestle Butterfinger',
    discountPrice: '$1.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F211%2Fnestle_kitkat.jpg&w=3840&q=75',
    name: 'Nestle Kitkat',
    discountPrice: '$1.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F212%2Fsnikers_slice.jpg&w=3840&q=75',
    name: 'Snikers Slice',
    discountPrice: '$3.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F213%2Fsnikers_snacksize.jpg&w=3840&q=75',
    name: 'Snikers Snack Size',
    discountPrice: '$3.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F214%2Fcottage_bbq.jpg&w=3840&q=75',
    name: 'Wise Cottage Fires Bbq',
    discountPrice: '$1.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F215%2Fcrisps-puzzle.jpg&w=3840&q=75',
    name: 'Puzzles Crips Ready Salted',
    discountPrice: '$0.60',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F216%2Fdoritos.jpg&w=3840&q=75',
    name: 'Doritos Tangy Cheese',
    discountPrice: '$1.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F217%2Flays_baked.jpg&w=3840&q=75',
    name: 'Lays Baked',
    discountPrice: '$1.50',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F218%2Flays_sea_salted.jpg&w=3840&q=75',
    name: 'Lays Sea Salted',
    discountPrice: '$1.20',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F219%2Flays-kettle-cooked.jpg&w=3840&q=75',
    name: 'Lays Kettle Cooked',
    discountPrice: '$1.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F220%2Flays-sour-cream.jpg&w=3840&q=75',
    name: 'Lays Sour Cream',
    discountPrice: '$1.50',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F221%2Fnims_apple_fruit.jpg&w=3840&q=75',
    name: 'Nims Apple Crisp',
    discountPrice: '$1.50',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F222%2FReady-Salted-Crisps.jpg&w=3840&q=75',
    name: 'Snack Rite Ready Saled',
    discountPrice: '$3.00',
    regularPrice: '$5.00',
    offerPercent: '40%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F223%2FRoysters_6pk.jpg&w=3840&q=75',
    name: 'Roysters Bubbled Crips',
    discountPrice: '$4.20',
    regularPrice: '$5.00',
    offerPercent: '16%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F224%2Fsnackrite_bags.jpg&w=3840&q=75',
    name: 'Snackrite Cheese Onion',
    discountPrice: '$5.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F225%2Ftayto_cheese_onion.jpg&w=3840&q=75',
    name: 'Tayto Cheese Onion',
    discountPrice: '$1.75',
    regularPrice: '$2.80',
    offerPercent: '37%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F226%2Ftayto_pickled_onion.jpg&w=3840&q=75',
    name: 'Tayto Pickled Onion',
    discountPrice: '$1.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F227%2Fwalkers_cheese_onion.jpg&w=3840&q=75',
    name: 'Walkers Cheese Onion',
    discountPrice: '$2.50',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F228%2Fcintan_chicken.jpg&w=3840&q=75',
    name: 'Cintan Chicken Noodles',
    discountPrice: '$4.00',
    regularPrice: '$5.00',
    offerPercent: '20%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F229%2Findomie_special_chicken.jpg&w=3840&q=75',
    name: 'Indomie Chicken Noodles',
    discountPrice: '$2.50',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F230%2Fkame_stir_fry.jpg&w=3840&q=75',
    name: 'Kame H Okkein Stir Fry Noodles',
    discountPrice: '$4.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F231%2Fkoka_curry.jpg&w=3840&q=75',
    name: 'Koka Curry Noodles',
    discountPrice: '$4.00',
    regularPrice: '$6.00',
    offerPercent: '33%',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F232%2Fmaggi_bbq.jpg&w=3840&q=75',
    name: 'Maggi Bbq Noodles',
    discountPrice: '$6.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F233%2Fmaggi_beef.jpg&w=3840&q=75',
    name: 'Maggi Beef Noodles',
    discountPrice: '$3.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F234%2Fmaggi_biriyani.jpg&w=3840&q=75',
    name: 'Maggi Biriyani Noodles',
    discountPrice: '$3.00',
    regularPrice: '',
    offerPercent: '',
    amount: 0,
  },{
    id: uuid4(),
    img: 'https://shop-pickbazar-rest.vercel.app/_next/image?url=https%3A%2F%2Fpickbazarlaravel.s3.ap-southeast-1.amazonaws.com%2F235%2Fmaggi_chicken.jpg&w=3840&q=75',
    name: 'Maggi Chicken Noodles',
    discountPrice: '$10.00',
    regularPrice: '$12.00',
    offerPercent: '17%',
    amount: 0,
  },
]
